name: Endpoint

on:
  workflow_dispatch:

jobs:
  endpoint-create: 
    runs-on: ubuntu-latest-16-cores
    environment: default
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - id: auth
      name: "Auth"
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.SA_EMAIL }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'
        
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Deploy ENDPOINT to Vertex AI
      run: | 
          MODEL_ID=$(gcloud ai models list --region europe-west4 --filter="displayName=tryggtekst" --format="value(name)" --sort-by=~create_time --limit=1)

          gcloud ai endpoints create --region europe-west4 --display-name "tryggtekst"

          
          ENDPOINT_ID=$(gcloud ai endpoints list --region=europe-west4 --format="value(name)" --sort-by=~create_time --limit=1)
          echo "printer endpoint id now"
          echo $ENDPOINT_ID
          echo $MODEL_ID
          echo "skal deploye endpoint"
          
          gcloud ai endpoints deploy-model $ENDPOINT_ID --region europe-west4 --machine-type a2-highgpu-1g --model $MODEL_ID --display-name "tryggtekst" --accelerator type=nvidia-tesla-a100,count=1
  endpoint-done:
    runs-on: ubuntu-latest
    needs: endpoint-create
    steps:
          - name: Wait for CREATING ENDPOINT job to finish
            run: |
              # Waits for the long-running job to complete
              while true; do sleep 60; done