
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy: 
    runs-on: ubuntu-latest
    environment: default
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.SA_EMAIL }}

    - name: 'laster-mappe'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'treningsfiler'
        destination: 'tiltak-mlops'
